### ISSUE TITLE
IPopUpLoginParams需要一个多租户参数tenant_id

### ISSUE THREAD

**Issue by baiheinet** [Authing/AuthingSSO#58]
export interface IPopUpLoginParams {
    scope?: string;
    responseMode?: string;
    responseType?: string;
    nonce?: string;
    state?: string;
    prompt: IPromptType;
}

希望能补充一个多租户参数tenant_id

**Comment by erniu** [comment]
此 SDK 已被 [authing-browser-sdk](https://github.com/Authing/authing-browser-sdk/) 替代，可以参考下对应的 [demo](https://github.com/Authing/authing-browser-sdk/tree/main/example/sso)
