### ISSUE TITLE
typescript 编译警告如何去除

### ISSUE THREAD

**Issue by lixiaoshun** [Authing/AuthingSSO#59]
![Uploading image.png…]()

**Comment by liaochangjiang** [comment]
看不到你上传的图片 ～ 麻烦把报错日志复制一下贴出来

**Comment by lixiaoshun** [comment]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/42568595/166426472-c72c0196-c38a-4200-a6cc-36758843ad32.png">

**Comment by lixiaoshun** [comment]
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/42568595/166426803-d5e41762-5999-4c74-bb20-43df639950b7.png">


WARNING in ./node_modules/@authing/sso/build/module/errors/AuthenticationError.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/AuthenticationError.ts' file: Error: ENOENT: no such file or directory, open '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/AuthenticationError.ts'
 @ ./node_modules/@authing/sso/build/module/index.js 144:0-67 150:0-67 150:0-67 384:26-45 391:24-43 442:21-40 486:24-43 519:16-35
 @ ./src/Authing.ts 4:0-42 6:20-30
 @ ./src/App.tsx 23:0-32 54:22-42 61:8-21 71:6-19
 @ ./src/index.tsx 7:0-24 9:38-41

WARNING in ./node_modules/@authing/sso/build/module/errors/AuthingSSOError.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/AuthingSSOError.ts' file: Error: ENOENT: no such file or directory, open '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/AuthingSSOError.ts'
 @ ./node_modules/@authing/sso/build/module/errors/InvalidParamsError.js 25:0-52 37:2-17
 @ ./node_modules/@authing/sso/build/module/index.js 143:0-65 151:0-65 151:0-65 170:16-34 174:16-34 178:16-34 368:24-42
 @ ./src/Authing.ts 4:0-42 6:20-30
 @ ./src/App.tsx 23:0-32 54:22-42 61:8-21 71:6-19
 @ ./src/index.tsx 7:0-24 9:38-41

WARNING in ./node_modules/@authing/sso/build/module/errors/InvalidParamsError.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/InvalidParamsError.ts' file: Error: ENOENT: no such file or directory, open '/Users/lisa/workpack/dashboard/node_modules/@authing/sso/src/errors/InvalidParamsError.ts'
 @ ./node_modules/@authing/sso/build/module/index.js 143:0-65 151:0-65 151:0-65 170:16-34 174:16-34 178:16-34 368:24-42
 @ ./src/Authing.ts 4:0-42 6:20-30
 @ ./src/App.tsx 23:0-32 54:22-42 61:8-21 71:6-19
 @ ./src/index.tsx 7:0-24 9:38-41

**Comment by liaochangjiang** [comment]
这个 warning 不会导致构建失败，如果想去掉这个 warning，可以参考 https://github.com/facebook/create-react-app/discussions/11767 描述的，设置 `GENERATE_SOURCEMAP` 为 `false`。

```
 "scripts": {
        "start": "GENERATE_SOURCEMAP=false react-scripts start",
```

后续我们会给 AuthingSSO 加上 sourcemap，加上之后会在此 issue 下通知你。
